modLoader = "kotlinforforge"
loaderVersion = "[3,)"
license = "MIT"

[[mods]]
modId = "allaybottle"
version = "1.1.1"
displayName = "Allay in a Bottle"
authors = "thepiguy"
description = '''
Allay in a Bottle
'''

[[dependencies.allaybottle]]
modId = "forge"
mandatory = true
versionRange = "[43,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.allaybottle]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19.3,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.allaybottle]]
modId = "architectury"
mandatory = true
versionRange = "[7.0.65,)"
ordering = "AFTER"
side = "BOTH"